/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorefrontRouteImport } from './routes/storefront'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiResetPasswordRouteImport } from './routes/api/reset-password'
import { Route as ApiForgotPasswordRouteImport } from './routes/api/forgot-password'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin-login'

const StorefrontRoute = StorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetPasswordRoute = ApiResetPasswordRouteImport.update({
  id: '/api/reset-password',
  path: '/api/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForgotPasswordRoute = ApiForgotPasswordRouteImport.update({
  id: '/api/forgot-password',
  path: '/api/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/storefront': typeof StorefrontRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/cron': typeof ApiCronRoute
  '/api/forgot-password': typeof ApiForgotPasswordRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/storefront': typeof StorefrontRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/cron': typeof ApiCronRoute
  '/api/forgot-password': typeof ApiForgotPasswordRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analytics': typeof AnalyticsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRoute
  '/coupons': typeof CouponsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/storefront': typeof StorefrontRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/cron': typeof ApiCronRoute
  '/api/forgot-password': typeof ApiForgotPasswordRoute
  '/api/reset-password': typeof ApiResetPasswordRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analytics'
    | '/checkout'
    | '/contact'
    | '/content'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/favorites'
    | '/forgot-password'
    | '/inbox'
    | '/login'
    | '/orders'
    | '/products'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/storefront'
    | '/api/admin-login'
    | '/api/cron'
    | '/api/forgot-password'
    | '/api/reset-password'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analytics'
    | '/checkout'
    | '/contact'
    | '/content'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/favorites'
    | '/forgot-password'
    | '/inbox'
    | '/login'
    | '/orders'
    | '/products'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/storefront'
    | '/api/admin-login'
    | '/api/cron'
    | '/api/forgot-password'
    | '/api/reset-password'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analytics'
    | '/checkout'
    | '/contact'
    | '/content'
    | '/coupons'
    | '/customers'
    | '/dashboard'
    | '/favorites'
    | '/forgot-password'
    | '/inbox'
    | '/login'
    | '/orders'
    | '/products'
    | '/reset-password'
    | '/settings'
    | '/shop'
    | '/storefront'
    | '/api/admin-login'
    | '/api/cron'
    | '/api/forgot-password'
    | '/api/reset-password'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRoute
  CouponsRoute: typeof CouponsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  StorefrontRoute: typeof StorefrontRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiForgotPasswordRoute: typeof ApiForgotPasswordRoute
  ApiResetPasswordRoute: typeof ApiResetPasswordRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storefront': {
      id: '/storefront'
      path: '/storefront'
      fullPath: '/storefront'
      preLoaderRoute: typeof StorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset-password': {
      id: '/api/reset-password'
      path: '/api/reset-password'
      fullPath: '/api/reset-password'
      preLoaderRoute: typeof ApiResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forgot-password': {
      id: '/api/forgot-password'
      path: '/api/forgot-password'
      fullPath: '/api/forgot-password'
      preLoaderRoute: typeof ApiForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyticsRoute: AnalyticsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRoute,
  CouponsRoute: CouponsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  StorefrontRoute: StorefrontRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiCronRoute: ApiCronRoute,
  ApiForgotPasswordRoute: ApiForgotPasswordRoute,
  ApiResetPasswordRoute: ApiResetPasswordRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
